# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cdfff01807c8a1c560302c55076043fa006a181511d4f9d795d4a3e6058ab2745d1fcb992253aaa88949aa7fa88f4e81e4b0cfcc0d60f42f50561123b4cfdc0

test:
  secret_key_base: c2fd616d289d60b45c31d336076c6f52743d7187767ea6a10416f2705bf83ad2ef6aa23ee914296179fad8ca4eb8bdf2a7246c8ed0576171b5b0f38db6b8297b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
